import '../models/user_role.dart';

const allPermissionKeys = [
  'users.view',
  'users.create',
  'users.edit',
  'users.delete',
  'orders.view',
  'orders.create',
  'orders.edit',
  'orders.delete',
  'inventory.view',
  'inventory.manage',
  'deliveries.view',
  'deliveries.manage',
  'customers.view',
  'customers.manage',
  'reports.view',
  'reports.export',
  'settings.view',
  'settings.manage',
];

final defaultRolePermissions = <UserRole, Map<String, bool>>{
  UserRole.admin: {for (final k in allPermissionKeys) k: true},
  UserRole.manager: {
    'users.view': true,
    'users.create': true,
    'users.edit': true,
    'users.delete': false,
    'orders.view': true,
    'orders.create': true,
    'orders.edit': true,
    'orders.delete': true,
    'inventory.view': true,
    'inventory.manage': true,
    'deliveries.view': true,
    'deliveries.manage': true,
    'customers.view': true,
    'customers.manage': true,
    'reports.view': true,
    'reports.export': true,
    'settings.view': true,
    'settings.manage': false,
  },
  UserRole.staff: {
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.delete': false,
    'orders.view': true,
    'orders.create': true,
    'orders.edit': true,
    'orders.delete': false,
    'inventory.view': true,
    'inventory.manage': false,
    'deliveries.view': true,
    'deliveries.manage': false,
    'customers.view': true,
    'customers.manage': true,
    'reports.view': true,
    'reports.export': false,
    'settings.view': true,
    'settings.manage': false,
  },
  UserRole.deliveryPersonnel: {
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.delete': false,
    'orders.view': true,
    'orders.create': false,
    'orders.edit': false,
    'orders.delete': false,
    'inventory.view': false,
    'inventory.manage': false,
    'deliveries.view': true,
    'deliveries.manage': true,
    'customers.view': true,
    'customers.manage': false,
    'reports.view': false,
    'reports.export': false,
    'settings.view': true,
    'settings.manage': false,
  },
  UserRole.customer: {
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.delete': false,
    'orders.view': true,
    'orders.create': true,
    'orders.edit': false,
    'orders.delete': false,
    'inventory.view': false,
    'inventory.manage': false,
    'deliveries.view': true,
    'deliveries.manage': false,
    'customers.view': false,
    'customers.manage': false,
    'reports.view': false,
    'reports.export': false,
    'settings.view': true,
    'settings.manage': false,
  },
};

bool hasPermission(UserRole role, String permission) {
  return defaultRolePermissions[role]?[permission] ?? false;
}
